### ISSUE TITLE
Python SDK Example

### ISSUE THREAD

**Issue by seanjhatch** [Logitech/logi_craft_sdk#3]
I am trying to view the python SDK example code however the link is just taking me to a page that says "error 404, page not found". Could this be fixed please?

**Comment by seanjhatch** [comment]
In fact, all the sample code is taking you to an error 404 page.

**Comment by naokihada** [comment]
Please refer to https://github.com/Logitech/logi_craft_sdk/tree/master/samples/CraftPython
for until broken link get fixed.
Thank you.

**Comment by rgopalakrishna** [comment]
Thanks for reporting the issue. We have addressed the issue. 
Please let us know of any further questions.
