### ISSUE TITLE
No option to "install  profile"

### ISSUE THREAD

**Issue by akimhobo** [Logitech/logi_craft_sdk#47]
This step in the instructions:
![image](https://user-images.githubusercontent.com/22689802/102306202-86e64380-3f16-11eb-88df-e5da9f218758.png)

Doesn't exist in the latest version of Logitech Options after hitting All Applications>+Add application

Is there a workaround? I'm using ver 8.36.86 in Developer mode

**Comment by marctdt** [comment]
Logitech Options 8 doesn't allow to install custom profiles. The workaround is to use the v7, install the profiles and reinstall the latest version of Options. The profiles should remain installed.

**Comment by akimhobo** [comment]
Thank you for the response, hopefully this feature continues to have future support, there are some longer term upsides in developing a community and a reputation
