### ISSUE TITLE
LogiOptionsMgr.exe bluetooth connection reset

### ISSUE THREAD

**Issue by mtbsgmz** [Logitech/logi_craft_sdk#7]
MX Anywhere 2 freezes in 2 seconds. constantly refreshing the bluetooth connection. Terminate task LogiOptionsMgr.exe with Task Manager. The error is recovering, but the special functions do not work.

**Comment by naokihada** [comment]
If it is not related Craft SDK, I think it's better to ask at Logitech Community.
https://community.logitech.com/
Thank you.
